<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
     <ProjectReference Include="../../sweetlib-collections/src/SweetLib.Collections/SweetLib.Collections.csproj" />
  </ItemGroup>

</Project>
